### ISSUE TITLE
OpenCV account blocked

### ISSUE THREAD

**Issue by tejus-gupta** [opencv-infrastructure/answers.opencv.org#30]
Hi everyone. 
I can't access my account. It says I got blocked. I don't know why. My username is tejus.

**Comment by LaurentBerger** [comment]
Sorry you were blocked and  I don't know why too.

**Comment by StevenPuttemans** [comment]
My best guess, you are a new user, and probably you got overviewed in the list of first topics, which contain a lot of spam. Sorry for the inconvenience!

**Comment by berak** [comment]
seems to have happened [here](http://answers.opencv.org/question/137649/training-classifier-freezes/) , too.

@tejus-gupta , again, apologies, human error. if you happen to have any link to a previous question, then there might be achance to restore the account

**Comment by tejus-gupta** [comment]
my account has been restored, thanks for the help :)

**Comment by AmberElferink** [comment]
I have the same thing. When I try to upvote an answer I get:
Sorry, you cannot upvote because your account is blocked.
Your account might be blocked in error - please contact the site administrators, if you think so.
I haven't spammed or anything. Can anything be done to fix this?
This once was the link to my account. I am still logged in so if I click on my name, this happens:
https://answers.opencv.org/users/419392/amberelferink/

**Comment by StevenPuttemans** [comment]
I just restored access to your account. Can you check if it works?

**Comment by AmberElferink** [comment]
Yes it does. Thank you!
