### ISSUE TITLE
 Internal server error

### ISSUE THREAD

**Issue by LaurentBerger** [opencv-infrastructure/answers.opencv.org#75]
Hi, 
There is a problem with thoses question

http://answers.opencv.org/question/211854/using-generalizedhoughtransform-with-python/

http://answers.opencv.org/question/211853/using-generalizedhoughtransform-with-python/

http://answers.opencv.org/question/211851/using-generalizedhoughtransform-with-python/

**Comment by mshabunin** [comment]
The user who asked those questions had some strange IP address field, so the question is added, but its content (revisions) not due to address parsing error. Reasked here: http://answers.opencv.org/question/211936/using-generalizedhoughtransform-with-python/

Recently I've enabled IP addresses detection in AskBot, so that it started detecting real users' address instead of server local address. I will disable it if it causes more problems in future.
